# Generated by Django 5.2.1 on 2025-06-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imcCalc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('imc', models.FloatField()),
                ('condicao', models.CharField(max_length=50)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
