# Generated by Django 5.2.1 on 2025-06-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
